version: "3.9"

services: 
  app:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile-Application
    expose: 
      - "80"
    networks: 
      - application-net
      #- host-net
    

  loadbalancer:
    image: nginx:latest
    depends_on: 
      - app
    ports: 
      - "80:80"
    volumes: 
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: 
      - application-net
      #- host-net

    

networks: 
  application-net:
    ipam:
      driver: default
      config: 
        - subnet: "10.150.1.0/24"
  #host-net:

