FROM golang:1.15.5 AS BUILDER

COPY ./src /opt/gosrc/

WORKDIR /opt/gosrc/

RUN go get -d -v

# Statically compile, to run on Scratch
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o simpleapp

### BUILD APP IMAGE
FROM scratch

COPY --from=BUILDER /opt/gosrc/simpleapp /go/bin/
WORKDIR /go/bin/

#RUN groupadd -r gorunner && useradd --no-log-init -r -g gorunner gorunner
#RUN chown gorunner:gorunner simpleapp && \
#    chmod +x simpleapp
#
#USER gorunner

USER 9876

CMD [ "./simpleapp" ]